# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script:
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: '$(System.DefaultWorkingDirectory)/P2-Angular'
  
- script: npm publish
  workingDirectory: '$(System.DefaultWorkingDirectory)/P2-Angular' 

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(4d58c592-1d2c-41cc-99ec-37f71536b901)'
    appType: 'webApp'
    WebAppName: 'WinnerTeamFrontEnd'
    package: '$(System.DefaultWorkingDirectory)/P2-Angular'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    TakeAppOfflineFlag: false

