# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  appDir: P2-Angular

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
    
- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: '$(appDir)'
  displayName: npm ci

- script: npx ng build --prod
  workingDirectory: $(appDir)
  displayName: npx ng build

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'Project2_Team3_SonarCloud'
#     organization: 'chriskeller94'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: 'chriskeller94_Project2_Team3'
#     cliProjectName: 'Project2_Team3'
#     cliSources: '$(appDir)/src'
#     extraProperties: |
#       sonar.coverage.exclusions=**/*.spec.ts
#       sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info
#   displayName: sonarcloud preparing analysis

# - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
#   workingDirectory: $(appDir)
#   continueOnError: true
#   displayName: ng test

# - task: SonarCloudAnalyze@1
#   displayName: sonarcloud analysis

# - task: SonarCloudPublish@1
#   displayName: sonarcloud publish results

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(4d58c592-1d2c-41cc-99ec-37f71536b901)'
    appType: 'webApp'
    WebAppName: 'WinnerTeamFrontEnd'
    packageForLinux: '$(appDir)/dist/*'
  displayName: deploy to azure web service